
from scripts.emailer import send_email
import streamlit as st
import os


st.set_page_config(page_title="GoAlgo AI Command Center", layout="wide")

st.title("📈 GoAlgo AI Command Center")
st.markdown("Welcome, CEO. Your AI Team is standing by for commands.")

tabs = st.tabs(["Overview", "Strategy", "Insights", "Backtest", "Live Data", "Reports", "Infra"])

with tabs[0]:
    st.header("🚦 Project Overview")
    st.write("This is your unified control center to manage AI-powered trading strategies.")

with tabs[1]:
    st.header("🧠 Strategy Engine")
    st.write("Plug in market regimes and trading logic via SimuGPT and QuantGPT.")

with tabs[2]:
    st.header("📊 Insights")
    st.write("Generated by DataGPT and cleaned by BackendGPT.")

with tabs[3]:
    st.header("🔁 Backtest")
    st.write("Run historical simulations with SimuGPT.")

with tabs[4]:
    st.header("📡 Live Market Data")
    st.write("Fetched and processed via DataGPT.")

with tabs[5]:
    st.header("📤 Export & Email Reports")
    st.write("EmailGPT handles all exports and communications.")

with tabs[6]:
    st.header("🔧 Infrastructure")
    st.write("InfraGPT keeps your app running and deployable.")
st.subheader("📬 Email Insight Report")

email_input = st.text_input("Enter your email address", placeholder="you@example.com")

if st.button("Send Report"):
    if not email_input:
        st.warning("Please enter a valid email address.")
    else:
        # Make sure the report file exists
        report_path = "reports/insight_report.pdf"

        if not os.path.exists(report_path):
            st.error("⚠️ Report file not found.")
        else:
            success, message = send_email(
                recipient_email=email_input,
                subject="📈 GoAlgo Insight Report",
                body="Hi,\n\nPlease find attached your daily GoAlgo insight report.\n\nBest,\nTeam GoAlgo",
                attachment_path=report_path
            )
            st.success(message) if success else st.error(message)

