
import streamlit as st

st.set_page_config(page_title="GoAlgo AI Command Center", layout="wide")

st.title("📈 GoAlgo AI Command Center")
st.markdown("Welcome, CEO. Your AI Team is standing by for commands.")

tabs = st.tabs(["Overview", "Strategy", "Insights", "Backtest", "Live Data", "Reports", "Infra"])

with tabs[0]:
    st.header("🚦 Project Overview")
    st.write("This is your unified control center to manage AI-powered trading strategies.")

with tabs[1]:
    st.header("🧠 Strategy Engine")
    st.write("Plug in market regimes and trading logic via SimuGPT and QuantGPT.")

with tabs[2]:
    st.header("📊 Insights")
    st.write("Generated by DataGPT and cleaned by BackendGPT.")

with tabs[3]:
    st.header("🔁 Backtest")
    st.write("Run historical simulations with SimuGPT.")

with tabs[4]:
    st.header("📡 Live Market Data")
    st.write("Fetched and processed via DataGPT.")

with tabs[5]:
    st.header("📤 Export & Email Reports")
    st.write("EmailGPT handles all exports and communications.")

with tabs[6]:
    st.header("🔧 Infrastructure")
    st.write("InfraGPT keeps your app running and deployable.")
