# utils/generate_pdf.py

from fpdf import FPDF
import os

def generate_sample_pdf(output_path="reports/insight_report.pdf"):
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", size=16)
    pdf.cell(200, 10, txt="GoAlgo AI Command Center", ln=True, align='C')
    pdf.ln(10)
    pdf.set_font("Arial", size=12)
    pdf.multi_cell(0, 10, txt="This is a demo report generated by GoAlgo AI Command Center. Insights will be here.")
    
    pdf.output(output_path)
