name: Daily Strategy Automation

on:
  schedule:
    - cron: '30 2 * * *'  # 🕒 Run every day at 08:00 IST (02:30 UTC)
  workflow_dispatch:       # ▶️ Manual run button in GitHub UI

jobs:
  generate-report:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run backtest & generate report
      run: python scripts/generate_report.py
